default:
  image: python:latest
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt



stages:
    - test

test:
  script:
    - python -m coverage run -m unittest
    - python -m coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: htmlcov/index.html